export const horariosDisponiveisV1 = [
	{ id: 0, hora: 0, indisponivel: false },
	{ id: 2, hora: 2, indisponivel: false },
	{ id: 3, hora: 3, indisponivel: false },
	{ id: 4, hora: 4, indisponivel: false },
	{ id: 5, hora: 5, indisponivel: false },
	{ id: 6, hora: 6, indisponivel: false },
	{ id: 7, hora: 7, indisponivel: false },
	{ id: 8, hora: 8, indisponivel: false },
	{ id: 9, hora: 9, indisponivel: false },
	{ id: 10, hora: 10, indisponivel: false },
	{ id: 11, hora: 11, indisponivel: false },
	{ id: 12, hora: 12, indisponivel: false },
	{ id: 13, hora: 13, indisponivel: false },
	{ id: 14, hora: 14, indisponivel: false },
	{ id: 15, hora: 15, indisponivel: false },
	{ id: 16, hora: 16, indisponivel: false },
	{ id: 17, hora: 17, indisponivel: false },
	{ id: 18, hora: 18, indisponivel: false },
	{ id: 19, hora: 19, indisponivel: false },
	{ id: 20, hora: 20, indisponivel: false },
	{ id: 21, hora: 21, indisponivel: false },
	{ id: 22, hora: 22, indisponivel: false },
	{ id: 23, hora: 23, indisponivel: false },
];
